<?php

/**
 * @file
 * Module adds a Wywisyg plugin for smart_paging.
 */

/**
 * Implements hook_wysiwyg_include_directory().
 */
function wysiwyg_smart_paging_wysiwyg_include_directory($type) {
  switch ($type) {
    case 'plugins':
      return $type;
  }
}

/**
 * Implements hook_page_alter().
 */
function wysiwyg_smart_paging_page_alter(&$page) {
  drupal_add_css(drupal_get_path('module', 'wysiwyg_smart_paging') .
          '/wysiwyg_smart_paging.css');
}

function wysiwyg_smart_paging_form() {
  if (!module_exists('metatag')) {
    $tags = array(
      'global' => array(
        'title', 'description', 'abstract', 'keywords',
      ),
      'open-graph' => array(
        'fb:admins', 'fb:app_id', 'og:title', 'og:description',
        'og:image', 'og:url', 'og:latitude', 'og:longitude',
        'og:street-address', 'og:locality', 'og:region', 'og:postal-code',
        'og:country-name', 'og:email', 'og:phone_number', 'og:fax_number',
        'og:video', 'og:video:secure_url', 'og:video:width', 'og:video:height',
      ),
      'advanced' => array(
        'news_keywords', 'copyright', 'image_src',
        'canonical', 'shortlink', 'publisher', 'author',
        'original-source_content',
      ),
    );
        
    $form = array();
    $weight = 0;
    foreach ($tags as $group_name => $group) {
      $form[$group_name] = array(
        '#type' => 'fieldset',
        '#title' => ucfirst($group_name),
        '#collapsible' => TRUE,
        '#collapsed' => ($group_name != 'global') ? TRUE : FALSE,
        '#weight' => $weight,
      );
      foreach ($group as $tag) {
        $form[$group_name][$tag] = array(
          '#type' => 'textfield',
          '#name' => 'meta_name_' . $tag . '_content',
          '#title' => $tag,
          '#size' => 70,
        );
      }
      $weight++;
    }
  }
  else {
    $form = wysiwyg_smart_paging_metatag_form();
  }
  
  $form['#prefix'] = '<div class="wysiwyg-sp-popup">' . '<h2>Edit Metatag</h2>';
  $form['#suffix'] = '</div>';
    
  $form['actions'] = array('#weight' => 100);
  $form['actions']['insert'] = array(
    '#type' => 'button',
    '#value' => t('Insert'),
    '#name' => 'insert',
    '#attributes' => array('class' => array('insert'),
      'onclick' => 'return (false);'),
  );
  $form['actions']['cancel'] = array(
    '#type' => 'button',
    '#value' => t('Cancel'),
    '#name' => 'cancel',
    '#attributes' => array('class' => array('cancel'),
      'onclick' => 'return (false);'),
  );

  return $form;
}

/**
 * Helper that gets the form from Metatags module.
 */
function wysiwyg_smart_paging_metatag_form() {
    module_load_include('inc', 'metatag', 'metatag.admin');
    drupal_add_css(drupal_get_path('module', 'metatag') . '/metatag.admin.css');
    drupal_add_js(drupal_get_path('module', 'metatag') . '/metatag.admin.js');
    
    $config = new stdClass();
    $config->cid = NULL;
    $config->instance = 'node:page';
    $config->config = array();
  
    $form = drupal_get_form('metatag_config_edit_form', $config);
    
    return $form;
}
